In [2]:
import json
import pandas as pd

In [3]:
with open('recipes.json') as f:
    recipes = json.load(f)

In [15]:
ingredients = set()
for recipe in recipes:
    ingredients = ingredients | set(recipe['ingredients'])
len(ingredients)

1318

In [16]:
df = pd.DataFrame(recipes)

In [17]:
df.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [18]:
type(df['ingredients'].iloc[0])

list

In [19]:
def find_item(cell):
    if item in cell:
        return 1
    return 0

In [20]:
for item in ingredients:
    df[item] = df['ingredients'].apply(find_item)

In [21]:
df.head()

,id,cuisine,ingredients,dried thyme,sesame paste,McCormick Parsley Flakes,fenugreek leaves,black olives,trout fillet,amchur,...,summer squash,mint leaves,bread flour,hoisin sauce,softened butter,english cucumber,bird chile,fresh salmon,napa cabbage leaves,barbecue sauce
0,10259,greek,"[romaine lettuce, black olives, grape tomatoes...",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,"[plain flour, ground pepper, salt, tomatoes, g...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,"[eggs, pepper, salt, mayonaise, cooking oil, g...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22213,indian,"[water, vegetable oil, wheat, salt]",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,"[black pepper, shallots, cornflour, cayenne pe...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df['ingredients'] = df['ingredients'].apply(lambda x: len(x))

In [23]:
df.head()

,id,cuisine,ingredients,dried thyme,sesame paste,McCormick Parsley Flakes,fenugreek leaves,black olives,trout fillet,amchur,...,summer squash,mint leaves,bread flour,hoisin sauce,softened butter,english cucumber,bird chile,fresh salmon,napa cabbage leaves,barbecue sauce
0,10259,greek,9,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22213,indian,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df.to_csv('recipes.csv', index=False)